# Dependabot configuration file
#
# Dependabot is used to check github actions.

---

version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
